name: Ignite Timer Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Ignite Timer
        run: npm run build

      - name: Deploy Ignite Timer
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist